import {
    Car, Bus, Fuel, Wrench, ParkingCircle, CarTaxiFront,
    Trash2, Droplets, Zap, Wifi, Phone,
    Briefcase, Megaphone, Users, Plane, FileText, Building, Package,
    BookOpen, GraduationCap, School,
    Ticket, Palette, Film, Music, Newspaper,
    Calculator, Scale, Banknote, CreditCard, Landmark,
    ShoppingCart, Utensils, Pizza, Beer, Coffee,
    Heart, Gift,
    Stethoscope, Eye, Dumbbell, Activity, Pill,
    Sofa, Hammer, Shield, Home, Droplet,
    Monitor, Scissors, Sparkles,
    Baby, ToyBrick,
    Shirt, ShoppingBag, Dog,
    AlertCircle, ArrowRightLeft, HelpCircle, LucideIcon,
    MapPin, Calendar, MoreHorizontal
} from "lucide-react"

export const EXPENSE_CATEGORIES: Record<string, { label: string; icon: LucideIcon }[]> = {
    "Auto & Transport": [
        { label: "Auto Payment", icon: Car },
        { label: "Public Transit", icon: Bus },
        { label: "Gas", icon: Fuel },
        { label: "Auto Maintenance", icon: Wrench },
        { label: "Parking & Tolls", icon: ParkingCircle },
        { label: "Taxi & Ride Shares", icon: CarTaxiFront },
    ],
    "Bills & Utilities": [
        { label: "Garbage", icon: Trash2 },
        { label: "Water", icon: Droplets },
        { label: "Gas & Electric", icon: Zap },
        { label: "Internet & Cable", icon: Wifi },
        { label: "Phone", icon: Phone },
    ],
    "Business": [
        { label: "Advertising & Promotion", icon: Megaphone },
        { label: "Business Utilities", icon: Wifi },
        { label: "Employee Wages", icon: Users },
        { label: "Business Travel", icon: Plane },
        { label: "Business Auto", icon: Car },
        { label: "Business Insurance", icon: Shield },
        { label: "Office Supplies", icon: Package },
        { label: "Office Rent", icon: Building },
        { label: "Postage & Shipping", icon: Package },
    ],
    "Education": [
        { label: "Books & Supplies", icon: BookOpen },
        { label: "Student Loans", icon: GraduationCap },
        { label: "Tuition", icon: School },
    ],
    "Entertainment": [
        { label: "Amusement", icon: Ticket },
        { label: "Arts", icon: Palette },
        { label: "Movies & DVDs", icon: Film },
        { label: "Music", icon: Music },
        { label: "Newspapers & Magazines", icon: Newspaper },
    ],
    "Financial": [
        { label: "Loan Repayment", icon: Banknote },
        { label: "Financial & Legal", icon: Scale },
        { label: "Financial Fees", icon: Calculator },
        { label: "Cash & ATM", icon: Banknote },
        { label: "Insurance", icon: Shield },
        { label: "Taxes", icon: FileText },
    ],
    "Food & Dining": [
        { label: "Groceries", icon: ShoppingCart },
        { label: "Restaurants", icon: Utensils },
        { label: "Fast Food", icon: Pizza },
        { label: "Alcohol & Bars", icon: Beer },
        { label: "Coffee Shops", icon: Coffee },
    ],
    "Gifts & Donations": [
        { label: "Charity", icon: Heart },
        { label: "Gifts", icon: Gift },
    ],
    "Health & Fitness": [
        { label: "Dentist", icon: Stethoscope },
        { label: "Doctor", icon: Stethoscope },
        { label: "Eyecare", icon: Eye },
        { label: "Gym", icon: Dumbbell },
        { label: "Health Insurance", icon: Activity },
        { label: "Pharmacy", icon: Pill },
    ],
    "Home": [
        { label: "Furnishings", icon: Sofa },
        { label: "Home Improvement", icon: Hammer },
        { label: "Home Insurance", icon: Shield },
        { label: "Home Services", icon: Home },
        { label: "HOA Dues", icon: Landmark },
        { label: "Home Supplies", icon: ShoppingCart },
        { label: "Lawn & Garden", icon: Droplet },
        { label: "Mortgage", icon: Home },
    ],
    "Technology": [
        { label: "Electronics & Software", icon: Monitor },
    ],
    "Personal Care": [
        { label: "Hair", icon: Scissors },
        { label: "Spa & Massage", icon: Sparkles },
        { label: "Beauty Products", icon: Sparkles },
    ],
    "Children": [
        { label: "Child Support", icon: Users },
        { label: "Childcare", icon: Baby },
        { label: "Kids Activities", icon: ToyBrick },
        { label: "Allowance", icon: Banknote },
        { label: "Toys", icon: ToyBrick },
    ],
    "Shopping": [
        { label: "Clothing", icon: Shirt },
        { label: "Sporting Goods", icon: Dumbbell },
        { label: "Pet Food & Supplies", icon: Dog },
        { label: "Personal & Lifestyle", icon: ShoppingBag },
        { label: "Subscriptions", icon: Calendar },
    ],
    "Travel": [
        { label: "Air Travel", icon: Plane },
        { label: "Accommodation", icon: Building },
        { label: "Rental Car & Taxi", icon: Car },
        { label: "Vacation", icon: MapPin },
    ],
    "Fees & Charges": [
        { label: "Bank Fees", icon: AlertCircle },
        { label: "Late Fees", icon: AlertCircle },
        { label: "Service Fees", icon: AlertCircle },
    ],
    "Transfers": [
        { label: "Transfer", icon: ArrowRightLeft },
        { label: "Credit Card Payment", icon: CreditCard },
    ],
    "Other": [
        { label: "Uncategorized", icon: HelpCircle },
        { label: "Miscellaneous", icon: MoreHorizontal },
    ]
}
